GET http://localhost:8080/metrics
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM2MjgxNjUzLCJ1c2VySWQiOjJ9.uwl-2xNePHLNHLpbVs5sh39wRYp2rx7raCiCpEBIeik 